---
abstract: 'Web server that just returns 503 Service unavailable'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-TrafficCone
requires:
  File::HomeDir: 0
  File::Spec: 0
  Mojo::Base: 0
  Mojo::URL: 0
  Mojolicious::Commands: 0
  YAML: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.02
